#!/bin/bash

FORCE_PUSH="force|delete|-f"
# force push を禁止するブランチを複数指定可能
PROTECTED_BRANCHES="(master|develop)"
PUSH_COMMAND=`ps -ocommand= -p $PPID`

while read local_ref local_sha1 remote_ref remote_sha1
do
    if [[ "${remote_ref##refs/heads/}" =~ $PROTECTED_BRANCHES && "$PUSH_COMMAND" =~ $FORCE_PUSH ]]; then
        echo "This force-push to the ${remote_ref##refs/heads/} branch has been blocked."
        echo "Get wild and tough!"
        # mac なら 標準装備の afplay で音楽再生可能
        afplay ~/.git_template/hooks/get-wild.mp3 -q 1
        exit 1
    fi
done

branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
    "$(git describe --contains --all HEAD)"

if [ "${branch##refs/heads/}" = "master" ]; then
    echo "Do not commit on the master branch!"
    echo "Get wild and tough!"
    afplay ~/.git_template/hooks/get-wild.mp3 -q 1
    exit 1
fi
