#!/bin/bash

FORCE_PUSH="force|delete|-f"
# force push を禁止するブランチを複数指定可能
PROTECTED_BRANCHES="(master|develop)"
PUSH_COMMAND=`ps -ocommand= -p $PPID`


branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
    "$(git describe --contains --all HEAD)"

if [ "${branch##refs/heads/}" = "master" ]; then
    echo "Do not commit on the master branch!"
    echo "Get wild and tough!"
    afplay ~/.git_template/hooks/get-wild.mp3 -q 1
    exit 1
fi
