#!/bin/bash

FORCE_PUSH="force|delete|-f"
# force push を禁止するブランチを複数指定可能
PROTECTED_BRANCHES="(master|develop)"
PUSH_COMMAND=`ps -ocommand= -p $PPID`


branch="$(git symbolic-ref HEAD 2>/dev/null)" || \
    "$(git describe --contains --all HEAD)"

if [ "${branch##refs/heads/}" = "master" ]; then
    echo "Do not commit on the master branch!"
    echo "Get wild and tough!!"
    if [ -f $GET_WILD_PATH ]; then
        afplay $GET_WHILD_PATH -q 1
    else
        echo "Not found Get wild and tough!!"
        echo "set environment variable GET_WILD_PATH."
        echo "ex)"
        echo "export GET_WILD_PATH=/path/to/get_wild.m4a"
    fi
    exit 1
fi
